name: CI CD
on:
  push:
    branches:
      - master
    paths:
      # trigger on .github since workflows changed
      - '.github/**'
      - 'public/**'
      - 'src/**'
      # trigger on package*.json since dependencies changed
      - package.json
      - package-lock.json
  pull_request:
    branches:
      - master
    paths:
      # trigger on .github since workflows changed
      - '.github/**'
      - 'public/**'
      - 'src/**'
      # trigger on package*.json since dependencies changed
      - package.json
      - package-lock.json

jobs:
  continuous_integration:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Check style rules
        run: npm run style
      - name: Run unit tests and generate coverage report
        run: npm run test:coverage
    timeout-minutes: 15
  continuous_deployment:
    name: Continuous deployment
    needs: [continuous_integration]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Configure git
        env:
          USER_NAME: github-actions
          USER_EMAIL: github-actions@users.noreply.github.com
          ORIGIN: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git remote set-url origin $ORIGIN
      - name: Deploy to GitHub Pages
        run: npm run deploy
    timeout-minutes: 30
